## Overview

This notebook harmonises the 3 selected National Travel Survey (NTS) datasets under a shared trip-purpose classification, and integrate the 3 datasets together to form the Behavioural Evidence Layer used in this framework.

The output shows the mobility representation including trip purpose distribution, trip start time distribution, and travel mode distribution.

Future modellers can add more mobility components into this framework.

## 1. Import Libraries

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

## 2. Set Up File Pathes

In [2]:
import sys
from pathlib import Path

# Find repository root (../..)
repo_root = Path.cwd().parents[1]

# Add repository root to Python import path
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))

In [3]:
project_root = Path.cwd().parents[1]

harmonised_path = project_root / "data" / "nts" / "harmonised"

output_path = project_root / "output" / "behavioural_evidence" / "nts_behavioural_evidence_layer.json"

## 3. Load Dataset

In [4]:
trip_purpose_file = harmonised_path / "nts0611a_trip_purpose_probability.json"

travel_mode_file = harmonised_path / "nts0409a_travel_mode_probability.json"

temporal_pattern_file = harmonised_path / "nts0502b_temporal_pattern_probability.json"

## 4. Integration

In [5]:
trip_purpose = pd.read_json(trip_purpose_file)

travel_mode = pd.read_json(travel_mode_file)

temporal_pattern = pd.read_json(temporal_pattern_file)

## 5. Verify Loaded Datasets

In [6]:
print("Trip Purpose")
display(trip_purpose.head())

print("Travel Mode")
display(travel_mode.head())

print("Temporal Pattern")
display(temporal_pattern.head())

Trip Purpose

,Year,Sex,Age,Commuting,Business,Education,Escort Education,Shopping,Other Escort,Personal Business,Visiting Friends at Private Home,Visiting Friends Elsewhere,Entertainment or Public Activity,Sport: Participate,Holiday: Base,Day Trip,Just Walk
0,2024,Female,0-4,0.003616,0.000701,0.327535,0.044123,0.031882,0.142315,0.075573,0.106521,0.043625,0.078185,0.035980,0.015151,0.041132,0.053662
1,2024,Female,5-11,0.003616,0.000701,0.327535,0.044123,0.031882,0.142315,0.075573,0.106521,0.043625,0.078185,0.035980,0.015151,0.041132,0.053662
2,2024,Female,12-17,0.026672,0.001690,0.304515,0.038551,0.056038,0.125005,0.074419,0.108590,0.051023,0.074196,0.031747,0.015177,0.040354,0.052022
3,2024,Female,18-22,0.180319,0.015662,0.117592,0.019347,0.189261,0.036292,0.071061,0.109007,0.080139,0.057312,0.007461,0.017746,0.035592,0.063210
4,2024,Female,23-34,0.187671,0.030108,0.019513,0.088612,0.184447,0.069928,0.074421,0.086093,0.055916,0.059392,0.006704,0.017174,0.035667,0.084355

Travel Mode

,Purpose,Bus in London,Car or van driver,Car or van passenger,London Underground,Motorcycle,Non-local bus,Other Private Transport,Other Public Transport,Other local bus,Pedal Cycle,Surface Rail,Taxi or minicab,Walk
0,Business,0.014149,0.686180,0.058015,0.021660,0.001818,0.000000,0.007440,0.002132,0.022984,0.018543,0.068402,0.011831,0.086845
1,Commuting,0.025553,0.543133,0.074081,0.036511,0.009322,0.000383,0.004601,0.004547,0.053567,0.041854,0.069340,0.010494,0.126616
2,Education or Escort Education,0.020506,0.234031,0.231633,0.005851,0.000177,0.000000,0.025720,0.001263,0.046675,0.011719,0.011596,0.006177,0.404653
3,Just Walk,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
4,Leisure,0.012548,0.379552,0.322847,0.012225,0.002348,0.001344,0.008854,0.002579,0.024635,0.024577,0.029235,0.016470,0.162787

Temporal Pattern

,Year,Trip purpose,0000 to 0059 (%),0100 to 0159 (%),0200 to 0259 (%),0300 to 0359 (%),0400 to 0459 (%),0500 to 0559 (%),0600 to 0659 (%),0700 to 0759 (%),0800 to 0859 (%),0900 to 0959 (%),1000 to 1059 (%),1100 to 1159 (%),1200 to 1259 (%),1300 to 1359 (%),1400 to 1459 (%),1500 to 1559 (%),1600 to 1659 (%),1700 to 1759 (%),1800 to 1859 (%),1900 to 1959 (%),2000 to 2059 (%),2100 to 2159 (%),2200 to 2259 (%),2300 to 2359 (%)
0,2023 to 2024,Commuting,0.002398,0.001482,0.001119,0.002186,0.008279,0.030587,0.079655,0.152645,0.133287,0.036580,0.018253,0.016312,0.021910,0.031366,0.034866,0.053839,0.103820,0.132614,0.062758,0.025427,0.017580,0.011319,0.013994,0.007721
1,2023 to 2024,Business,0.000414,0.000152,0.000609,0.000819,0.002210,0.010750,0.045892,0.086967,0.112680,0.074659,0.060100,0.075560,0.065529,0.066300,0.063431,0.071627,0.091234,0.074635,0.039917,0.019221,0.015184,0.011300,0.006989,0.003822
2,2023 to 2024,Education,0.000000,0.000000,0.000000,0.000306,0.000044,0.000112,0.002540,0.097998,0.377559,0.017586,0.009686,0.011606,0.014716,0.008445,0.027963,0.332816,0.054838,0.026740,0.007727,0.004711,0.002080,0.001865,0.000498,0.000166
3,2023 to 2024,Escort Education,0.000000,0.000000,0.000071,0.000129,0.000049,0.000220,0.001812,0.051490,0.387148,0.034087,0.003753,0.012108,0.010911,0.005194,0.093015,0.309636,0.052116,0.028840,0.005281,0.002605,0.000963,0.000209,0.000304,0.000058
4,2023 to 2024,Shopping,0.000166,0.000024,0.000000,0.000000,0.000011,0.000479,0.003359,0.012883,0.031816,0.072451,0.117920,0.124450,0.111161,0.093734,0.087138,0.075723,0.072696,0.064742,0.057175,0.042038,0.021337,0.007617,0.002203,0.000876

In [7]:
print(trip_purpose.shape)
print(travel_mode.shape)
print(temporal_pattern.shape)

(18, 17)
(9, 14)
(8, 26)

## 6. Behaviour Integration

### 6.1 Trip Purpose Mapping

In [8]:
from ontology.nts_purpose_mapping import nts_purpose_mapping

### 6.2 NTS0611 Trip-Purpose Distribution Extraction

In [9]:
def extract_nts0611a_trip_purpose_distribution(
    shared_trip_purpose,
):
    nts0611a_trip_purpose_distribution = (
        trip_purpose[
            [
                "Year",
                "Sex",
                "Age",
                shared_trip_purpose,
            ]
        ].copy()
    )

    nts0611a_trip_purpose_distribution.rename(
        columns={
            shared_trip_purpose: (
                "Trip Purpose Probability"
            )
        },
        inplace=True,
    )

    return nts0611a_trip_purpose_distribution

In [10]:
nts0611_business = extract_nts0611a_trip_purpose_distribution(
    shared_trip_purpose="Business")

nts0611_business.head()

   Year     Sex    Age  Trip Purpose Probability
0  2024  Female    0-4                  0.000701
1  2024  Female   5-11                  0.000701
2  2024  Female  12-17                  0.001690
3  2024  Female  18-22                  0.015662
4  2024  Female  23-34                  0.030108

### 6.3 NTS0409a Travel-Mode Distribution Extraction

In [11]:
def extract_nts0409a_travel_mode_distribution(
    shared_trip_purpose,
):
    
    nts0409a_mapped_purposes = (
        nts_purpose_mapping[
            shared_trip_purpose
        ]["nts0409a"]
    )

    nts0409a_travel_mode_distribution = (
        travel_mode[
            travel_mode["Purpose"].isin(
                nts0409a_mapped_purposes
            )
        ].copy()
    )

    return nts0409a_travel_mode_distribution

In [12]:
nts0409_business = extract_nts0409a_travel_mode_distribution(
    shared_trip_purpose="Business")

nts0409_business.head()

,Purpose,Bus in London,Car or van driver,Car or van passenger,London Underground,Motorcycle,Non-local bus,Other Private Transport,Other Public Transport,Other local bus,Pedal Cycle,Surface Rail,Taxi or minicab,Walk
0,Business,0.014149,0.68618,0.058015,0.02166,0.001818,0.0,0.00744,0.002132,0.022984,0.018543,0.068402,0.011831,0.086845

### 6.4 NTS0502b Temporal-Pattern Distribution Extraction

In [13]:
def extract_nts0502b_temporal_distribution(
    shared_trip_purpose,
):
    
    nts0502b_mapped_purposes = (
        nts_purpose_mapping[
            shared_trip_purpose
        ]["nts0502b"]
    )

    nts0502b_trip_start_time_distribution = (
        temporal_pattern[
            temporal_pattern[
                "Trip purpose"
            ].isin(
                nts0502b_mapped_purposes
            )
        ].copy()
    )

    return nts0502b_trip_start_time_distribution

In [14]:
nts0502b_business_distribution = (
    extract_nts0502b_temporal_distribution(
        "Business"
    )
)

nts0502b_business_distribution

,Year,Trip purpose,0000 to 0059 (%),0100 to 0159 (%),0200 to 0259 (%),0300 to 0359 (%),0400 to 0459 (%),0500 to 0559 (%),0600 to 0659 (%),0700 to 0759 (%),0800 to 0859 (%),0900 to 0959 (%),1000 to 1059 (%),1100 to 1159 (%),1200 to 1259 (%),1300 to 1359 (%),1400 to 1459 (%),1500 to 1559 (%),1600 to 1659 (%),1700 to 1759 (%),1800 to 1859 (%),1900 to 1959 (%),2000 to 2059 (%),2100 to 2159 (%),2200 to 2259 (%),2300 to 2359 (%)
1,2023 to 2024,Business,0.000414,0.000152,0.000609,0.000819,0.00221,0.01075,0.045892,0.086967,0.11268,0.074659,0.0601,0.07556,0.065529,0.0663,0.063431,0.071627,0.091234,0.074635,0.039917,0.019221,0.015184,0.0113,0.006989,0.003822

### 6.5 Harmonised NTS Evidence Assembly

In [15]:
def assemble_harmonised_nts_evidence(
    shared_trip_purpose,
):
    
    nts0611a_trip_purpose_distribution = (
        extract_nts0611a_trip_purpose_distribution(
            shared_trip_purpose
        )
    )

    nts0502b_temporal_distribution = (
        extract_nts0502b_temporal_distribution(
            shared_trip_purpose
        )
    )

    nts0409a_travel_mode_distribution = (
        extract_nts0409a_travel_mode_distribution(
            shared_trip_purpose
        )
    )

    return {
        "nts0611a_trip_purpose_distribution": (
            nts0611a_trip_purpose_distribution
        ),
        "nts0502b_temporal_distribution": (
            nts0502b_temporal_distribution
        ),
        "nts0409a_travel_mode_distribution": (
            nts0409a_travel_mode_distribution
        ),
    }

In [16]:
business_nts_evidence = (
    assemble_harmonised_nts_evidence(
        "Business"
    )
)

business_nts_evidence.keys()

dict_keys(['nts0611a_trip_purpose_distribution', 'nts0502b_temporal_distribution', 'nts0409a_travel_mode_distribution'])

In [17]:
business_nts_evidence[
    "nts0611a_trip_purpose_distribution"
].head()

   Year     Sex    Age  Trip Purpose Probability
0  2024  Female    0-4                  0.000701
1  2024  Female   5-11                  0.000701
2  2024  Female  12-17                  0.001690
3  2024  Female  18-22                  0.015662
4  2024  Female  23-34                  0.030108

In [18]:
business_nts_evidence[
    "nts0409a_travel_mode_distribution"
]

,Purpose,Bus in London,Car or van driver,Car or van passenger,London Underground,Motorcycle,Non-local bus,Other Private Transport,Other Public Transport,Other local bus,Pedal Cycle,Surface Rail,Taxi or minicab,Walk
0,Business,0.014149,0.68618,0.058015,0.02166,0.001818,0.0,0.00744,0.002132,0.022984,0.018543,0.068402,0.011831,0.086845

In [19]:
business_nts_evidence[
    "nts0502b_temporal_distribution"
]

,Year,Trip purpose,0000 to 0059 (%),0100 to 0159 (%),0200 to 0259 (%),0300 to 0359 (%),0400 to 0459 (%),0500 to 0559 (%),0600 to 0659 (%),0700 to 0759 (%),0800 to 0859 (%),0900 to 0959 (%),1000 to 1059 (%),1100 to 1159 (%),1200 to 1259 (%),1300 to 1359 (%),1400 to 1459 (%),1500 to 1559 (%),1600 to 1659 (%),1700 to 1759 (%),1800 to 1859 (%),1900 to 1959 (%),2000 to 2059 (%),2100 to 2159 (%),2200 to 2259 (%),2300 to 2359 (%)
1,2023 to 2024,Business,0.000414,0.000152,0.000609,0.000819,0.00221,0.01075,0.045892,0.086967,0.11268,0.074659,0.0601,0.07556,0.065529,0.0663,0.063431,0.071627,0.091234,0.074635,0.039917,0.019221,0.015184,0.0113,0.006989,0.003822

In [20]:
assembled_nts_evidence = {}

for shared_trip_purpose in nts_purpose_mapping:

    assembled_nts_evidence[
        shared_trip_purpose
    ] = assemble_harmonised_nts_evidence(
        shared_trip_purpose
    )

## 7. Validation

In [21]:
len(assembled_nts_evidence)

14

In [22]:
assembled_nts_evidence.keys()

dict_keys(['Commuting', 'Business', 'Education', 'Escort Education', 'Shopping', 'Other Escort', 'Personal Business', 'Visiting Friends at Private Home', 'Visiting Friends Elsewhere', 'Entertainment or Public Activity', 'Sport: Participate', 'Holiday: Base', 'Day Trip', 'Just Walk'])

In [23]:
assembled_nts_evidence["Personal Business"]

{'nts0611a_trip_purpose_distribution':     Year     Sex    Age  Trip Purpose Probability
 0   2024  Female    0-4                  0.075573
 1   2024  Female   5-11                  0.075573
 2   2024  Female  12-17                  0.074419
 3   2024  Female  18-22                  0.071061
 4   2024  Female  23-34                  0.074421
 5   2024  Female  35-49                  0.075522
 6   2024  Female  50-64                  0.105210
 7   2024  Female  65-74                  0.141740
 8   2024  Female    75+                  0.159272
 9   2024    Male    0-4                  0.068052
 10  2024    Male   5-11                  0.068052
 11  2024    Male  12-17                  0.070062
 12  2024    Male  18-22                  0.075539
 13  2024    Male  23-34                  0.068595
 14  2024    Male  35-49                  0.073757
 15  2024    Male  50-64                  0.089951
 16  2024    Male  65-74                  0.125429
 17  2024    Male    75+                  0.141036,
 'nts0502b_temporal_distribution':            Year                                    Trip purpose  \
 5  2023 to 2024  Other Work, Other Escort and Personal Business

    0000 to 0059 (%)  0100 to 0159 (%)  0200 to 0259 (%)  0300 to 0359 (%)  \
 5          0.000689          0.000234          0.000224          0.000071

    0400 to 0459 (%)  0500 to 0559 (%)  0600 to 0659 (%)  0700 to 0759 (%)  \
 5          0.000904          0.002833          0.009161          0.043429

    0800 to 0859 (%)  0900 to 0959 (%)  1000 to 1059 (%)  1100 to 1159 (%)  \
 5          0.093261          0.074097          0.076766          0.074615

    1200 to 1259 (%)  1300 to 1359 (%)  1400 to 1459 (%)  1500 to 1559 (%)  \
 5          0.081419          0.070155          0.067627          0.083308

    1600 to 1659 (%)  1700 to 1759 (%)  1800 to 1859 (%)  1900 to 1959 (%)  \
 5          0.090202          0.085803          0.059412          0.039304

    2000 to 2059 (%)  2100 to 2159 (%)  2200 to 2259 (%)  2300 to 2359 (%)
 5          0.023725           0.01153          0.007551          0.003681  ,
 'nts0409a_travel_mode_distribution':              Purpose  Bus in London  Car or van driver  Car or van passenger  \
 7  Personal Business       0.016379           0.425456               0.22289

    London Underground  Motorcycle  Non-local bus  Other Private Transport  \
 7            0.006716    0.000799         0.0002                 0.008118

    Other Public Transport  Other local bus  Pedal Cycle  Surface Rail  \
 7                0.001792         0.031427     0.009595      0.011557

    Taxi or minicab      Walk
 7         0.014737  0.250334  }

In [24]:
for purpose, profile in assembled_nts_evidence.items():
    print(
        purpose,
        len(profile["nts0611a_trip_purpose_distribution"]),
        len(profile["nts0502b_temporal_distribution"]),
        len(profile["nts0409a_travel_mode_distribution"])
        
    )

Commuting 18 1 1
Business 18 1 1
Education 18 1 1
Escort Education 18 1 1
Shopping 18 1 1
Other Escort 18 1 1
Personal Business 18 1 1
Visiting Friends at Private Home 18 1 1
Visiting Friends Elsewhere 18 1 1
Entertainment or Public Activity 18 1 1
Sport: Participate 18 1 1
Holiday: Base 18 1 1
Day Trip 18 1 1
Just Walk 18 1 1

## 8. Export

In [25]:
import json

export_evidence = {}

for shared_trip_purpose, evidence in assembled_nts_evidence.items():

    export_evidence[shared_trip_purpose] = {

        "nts0611a_trip_purpose_distribution": evidence[
            "nts0611a_trip_purpose_distribution"
        ].to_dict(
            orient="records"
        ),

        "nts0502b_temporal_distribution": evidence[
            "nts0502b_temporal_distribution"
        ].to_dict(
            orient="records"
        ),

        "nts0409a_travel_mode_distribution": evidence[
            "nts0409a_travel_mode_distribution"
        ].to_dict(
            orient="records"
        ),
    }

In [26]:
Path(output_path).parent.mkdir(
    parents=True,
    exist_ok=True
)

with open(output_path, "w", encoding="utf-8") as f:

    json.dump(
        export_evidence,
        f,
        indent=4,
        ensure_ascii=False,
    )

print(
    "Harmonised NTS evidence exported to:"
    f"\n{output_path}"
)

Harmonised NTS evidence exported to:
c:\Users\user\OneDrive - University of Stirling\Desktop\dissertation\mobility-modelling-framework\output\behavioural_evidence\nts_behavioural_evidence_layer.json