## Overview

This notebook integrates the processed behavioural probability datasets into a unified behaviour representation.

The integration combines three National Travel Survey (NTS) datasets:

- Trip Purpose Probability (NTS0611)
- Temporal Pattern Probability (NTS0502)
- Travel Mode Probability (NTS0409)

As the trip purpose classifications differ across the three datasets, a predefined purpose mapping is applied to harmonise the categories before integration.

For each trip purpose defined in NTS0611, the corresponding temporal pattern and travel mode probability distributions are retrieved from the mapped NTS0502 and NTS0409 datasets.

The output of this notebook is an integrated behavioural probability dataset, which will be used as the behavioural input for the subsequent Opportunity Layer.

The resulting integrated behavioural probability dataset provides a consistent representation of trip purpose, temporal travel patterns, and travel mode distributions. It serves as the behavioural component of the proposed mobility modelling framework and provides the probabilistic inputs required by the Opportunity Layer.

## 1. Import Libraries

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

## 2. Set Up File Pathes

In [2]:
from pathlib import Path

project_root = Path.cwd().parents[1]

harmonised_path = project_root / "data" / "nts" / "harmonised"

## 3. Load Dataset

In [3]:
trip_purpose_file = harmonised_path / "nts0611_trip_purpose_probability.json"

travel_mode_file = harmonised_path / "nts0409_travel_mode_probability.json"

temporal_pattern_file = harmonised_path / "nts0502_temporal_pattern_probability.json"

## 4. Integration

In [4]:
trip_purpose = pd.read_json(trip_purpose_file)

travel_mode = pd.read_json(travel_mode_file)

temporal_pattern = pd.read_json(temporal_pattern_file)

## 5. Verify Loaded Datasets

In [5]:
print("Trip Purpose")
display(trip_purpose.head())

print("Travel Mode")
display(travel_mode.head())

print("Temporal Pattern")
display(temporal_pattern.head())

Trip Purpose

,Year,Sex [note 2],Age,Commuting,Business,Education,Escort Education,Shopping,Other Escort,Personal Business,Visiting Friends at Private Home,Visiting Friends Elsewhere,Entertainment or Public Activity,Sport: Participate,Holiday: Base,Day Trip,Just Walk
0,2024,Females,0-4,0.003616,0.000701,0.327535,0.044123,0.031882,0.142315,0.075573,0.106521,0.043625,0.078185,0.035980,0.015151,0.041132,0.053662
1,2024,Females,5-11,0.003616,0.000701,0.327535,0.044123,0.031882,0.142315,0.075573,0.106521,0.043625,0.078185,0.035980,0.015151,0.041132,0.053662
2,2024,Females,12-17,0.026672,0.001690,0.304515,0.038551,0.056038,0.125005,0.074419,0.108590,0.051023,0.074196,0.031747,0.015177,0.040354,0.052022
3,2024,Females,18-22,0.180319,0.015662,0.117592,0.019347,0.189261,0.036292,0.071061,0.109007,0.080139,0.057312,0.007461,0.017746,0.035592,0.063210
4,2024,Females,23-34,0.187671,0.030108,0.019513,0.088612,0.184447,0.069928,0.074421,0.086093,0.055916,0.059392,0.006704,0.017174,0.035667,0.084355

Travel Mode

,Purpose,Bus in London,Car or van driver,Car or van passenger,London Underground,Motorcycle,Non-local bus,Other local bus,Other private transport [note 6],Other public transport [note 7],Pedal cycle [note 5],Surface Rail,Taxi or minicab,"Walk [notes 3, 4]"
0,Business,0.014149,0.686180,0.058015,0.021660,0.001818,0.000000,0.022984,0.007440,0.002132,0.018543,0.068402,0.011831,0.086845
1,Commuting,0.025553,0.543133,0.074081,0.036511,0.009322,0.000383,0.053567,0.004601,0.004547,0.041854,0.069340,0.010494,0.126616
2,Education or Escort Education,0.020506,0.234031,0.231633,0.005851,0.000177,0.000000,0.046675,0.025720,0.001263,0.011719,0.011596,0.006177,0.404653
3,Just Walk,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
4,Leisure,0.012548,0.379552,0.322847,0.012225,0.002348,0.001344,0.024635,0.008854,0.002579,0.024577,0.029235,0.016470,0.162787

Temporal Pattern

,Year [note 2],Trip purpose,0000 to 0059 (%),0100 to 0159 (%),0200 to 0259 (%),0300 to 0359 (%),0400 to 0459 (%),0500 to 0559 (%),0600 to 0659 (%),0700 to 0759 (%),0800 to 0859 (%),0900 to 0959 (%),1000 to 1059 (%),1100 to 1159 (%),1200 to 1259 (%),1300 to 1359 (%),1400 to 1459 (%),1500 to 1559 (%),1600 to 1659 (%),1700 to 1759 (%),1800 to 1859 (%),1900 to 1959 (%),2000 to 2059 (%),2100 to 2159 (%),2200 to 2259 (%),2300 to 2359 (%)
0,2023 to 2024,Commuting,0.002398,0.001482,0.001119,0.002186,0.008279,0.030587,0.079655,0.152645,0.133287,0.036580,0.018253,0.016312,0.021910,0.031366,0.034866,0.053839,0.103820,0.132614,0.062758,0.025427,0.017580,0.011319,0.013994,0.007721
1,2023 to 2024,Business,0.000414,0.000152,0.000609,0.000819,0.002210,0.010750,0.045892,0.086967,0.112680,0.074659,0.060100,0.075560,0.065529,0.066300,0.063431,0.071627,0.091234,0.074635,0.039917,0.019221,0.015184,0.011300,0.006989,0.003822
2,2023 to 2024,Education,0.000000,0.000000,0.000000,0.000306,0.000044,0.000112,0.002540,0.097998,0.377559,0.017586,0.009686,0.011606,0.014716,0.008445,0.027963,0.332816,0.054838,0.026740,0.007727,0.004711,0.002080,0.001865,0.000498,0.000166
3,2023 to 2024,Escort Education,0.000000,0.000000,0.000071,0.000129,0.000049,0.000220,0.001812,0.051490,0.387148,0.034087,0.003753,0.012108,0.010911,0.005194,0.093015,0.309636,0.052116,0.028840,0.005281,0.002605,0.000963,0.000209,0.000304,0.000058
4,2023 to 2024,Shopping,0.000166,0.000024,0.000000,0.000000,0.000011,0.000479,0.003359,0.012883,0.031816,0.072451,0.117920,0.124450,0.111161,0.093734,0.087138,0.075723,0.072696,0.064742,0.057175,0.042038,0.021337,0.007617,0.002203,0.000876

In [6]:
print(trip_purpose.shape)
print(travel_mode.shape)
print(temporal_pattern.shape)

(18, 17)
(9, 14)
(8, 26)

## 6. Behaviour Integration

### 6.1 Trip Purpose Mapping

In [7]:
purpose_mapping = {

    "Commuting": {
        "nts0502": ["Commuting"],
        "nts0409": ["Commuting"]
    },

    "Business": {
        "nts0502": ["Business"],
        "nts0409": ["Business"]
    },

    "Education": {
        "nts0502": ["Education"],
        "nts0409": ["Education or Escort Education"]
    },

    "Escort Education": {
        "nts0502": ["Escort Education"],
        "nts0409": ["Education or Escort Education"]
    },

    "Shopping": {
        "nts0502": ["Shopping"],
        "nts0409": ["Shopping"]
    },

    "Other Escort": {
        "nts0502": ["Other Work, Other Escort and Personal Business"],
        "nts0409": ["Other Escort"]
    },

    "Personal Business": {
        "nts0502": ["Other Work, Other Escort and Personal Business"],
        "nts0409": ["Personal Business"]
    },

    "Visiting Friends at Private Home": {
        "nts0502": ["Visiting Friends, Entertainment and Sport"],
        "nts0409": ["Leisure"]
    },

    "Visiting Friends Elsewhere": {
        "nts0502": ["Visiting Friends, Entertainment and Sport"],
        "nts0409": ["Leisure"]
    },

    "Entertainment or Public Activity": {
        "nts0502": ["Visiting Friends, Entertainment and Sport"],
        "nts0409": ["Leisure"]
    },

    "Sport: Participate": {
        "nts0502": ["Visiting Friends, Entertainment and Sport"],
        "nts0409": ["Leisure"]
    },

    "Holiday: Base": {
        "nts0502": ["Holiday, Day Trip and Other"],
        "nts0409": ["Leisure"]
    },

    "Day Trip": {
        "nts0502": ["Holiday, Day Trip and Other"],
        "nts0409": ["Leisure"]
    },

    "Just Walk": {
        "nts0502": ["Holiday, Day Trip and Other"],
        "nts0409": ["Just Walk"]
    },


}

In [8]:
travel_mode.loc[
    travel_mode["Purpose"].str.contains("Personal", case=False),
    "Purpose"
]

7    Personal Business
Name: Purpose, dtype: object

In [9]:
purpose_mapping["Education"]

{'nts0502': ['Education'], 'nts0409': ['Education or Escort Education']}

In [10]:
purpose_mapping["Holiday: Base"]

{'nts0502': ['Holiday, Day Trip and Other'], 'nts0409': ['Leisure']}

### Step 6.2 Baseline Profile Extraction

In [11]:
def extract_baseline_profile(unified_purpose):
    """
    Extract the baseline trip purpose profile from NTS0611.
    """

    profile = trip_purpose[
        ["Year", "Sex [note 2]", "Age", unified_purpose]
    ].copy()

    profile.rename(
        columns={
            unified_purpose: "Trip Purpose Probability"
        },
        inplace=True
    )

    return profile

In [12]:
business_profile = extract_baseline_profile("Business")
business_profile

    Year Sex [note 2]    Age  Trip Purpose Probability
0   2024      Females    0-4                  0.000701
1   2024      Females   5-11                  0.000701
2   2024      Females  12-17                  0.001690
3   2024      Females  18-22                  0.015662
4   2024      Females  23-34                  0.030108
5   2024      Females  35-49                  0.030173
6   2024      Females  50-64                  0.032095
7   2024      Females  65-74                  0.013056
8   2024      Females    75+                  0.003727
9   2024        Males    0-4                  0.000525
10  2024        Males   5-11                  0.000525
11  2024        Males  12-17                  0.001834
12  2024        Males  18-22                  0.020638
13  2024        Males  23-34                  0.041704
14  2024        Males  35-49                  0.048323
15  2024        Males  50-64                  0.052414
16  2024        Males  65-74                  0.024487
17  2024        Males    75+                  0.007353

In [13]:
holiday_profile = extract_baseline_profile("Holiday: Base")
holiday_profile

    Year Sex [note 2]    Age  Trip Purpose Probability
0   2024      Females    0-4                  0.015151
1   2024      Females   5-11                  0.015151
2   2024      Females  12-17                  0.015177
3   2024      Females  18-22                  0.017746
4   2024      Females  23-34                  0.017174
5   2024      Females  35-49                  0.011911
6   2024      Females  50-64                  0.013860
7   2024      Females  65-74                  0.013501
8   2024      Females    75+                  0.012737
9   2024        Males    0-4                  0.012175
10  2024        Males   5-11                  0.012175
11  2024        Males  12-17                  0.012294
12  2024        Males  18-22                  0.015576
13  2024        Males  23-34                  0.017867
14  2024        Males  35-49                  0.013098
15  2024        Males  50-64                  0.015143
16  2024        Males  65-74                  0.013933
17  2024        Males    75+                  0.012863

### 6.3 Travel Mode Mapping

In [14]:
def extract_travel_mode(unified_purpose):
    """
    Extract travel mode probabilities from NTS0409
    using the trip purpose mapping.
    """

    mapped_purposes = purpose_mapping[unified_purpose]["nts0409"]

    profile = travel_mode[
        travel_mode["Purpose"].isin(mapped_purposes)
    ].copy()

    return profile

In [15]:
extract_travel_mode("Business")

,Purpose,Bus in London,Car or van driver,Car or van passenger,London Underground,Motorcycle,Non-local bus,Other local bus,Other private transport [note 6],Other public transport [note 7],Pedal cycle [note 5],Surface Rail,Taxi or minicab,"Walk [notes 3, 4]"
0,Business,0.014149,0.68618,0.058015,0.02166,0.001818,0.0,0.022984,0.00744,0.002132,0.018543,0.068402,0.011831,0.086845

In [16]:
extract_travel_mode("Personal Business")

,Purpose,Bus in London,Car or van driver,Car or van passenger,London Underground,Motorcycle,Non-local bus,Other local bus,Other private transport [note 6],Other public transport [note 7],Pedal cycle [note 5],Surface Rail,Taxi or minicab,"Walk [notes 3, 4]"
7,Personal Business,0.016379,0.425456,0.22289,0.006716,0.000799,0.0002,0.031427,0.008118,0.001792,0.009595,0.011557,0.014737,0.250334

### 6.4 Temporal Pattern Mapping

In [17]:
def extract_temporal_pattern(unified_purpose):
    """
    Extract temporal pattern probabilities from NTS0502
    using the trip purpose mapping.
    """

    mapped_purposes = purpose_mapping[unified_purpose]["nts0502"]

    profile = temporal_pattern[
        temporal_pattern["Trip purpose"].isin(mapped_purposes)
    ].copy()

    return profile

In [18]:
extract_temporal_pattern("Business")

,Year [note 2],Trip purpose,0000 to 0059 (%),0100 to 0159 (%),0200 to 0259 (%),0300 to 0359 (%),0400 to 0459 (%),0500 to 0559 (%),0600 to 0659 (%),0700 to 0759 (%),0800 to 0859 (%),0900 to 0959 (%),1000 to 1059 (%),1100 to 1159 (%),1200 to 1259 (%),1300 to 1359 (%),1400 to 1459 (%),1500 to 1559 (%),1600 to 1659 (%),1700 to 1759 (%),1800 to 1859 (%),1900 to 1959 (%),2000 to 2059 (%),2100 to 2159 (%),2200 to 2259 (%),2300 to 2359 (%)
1,2023 to 2024,Business,0.000414,0.000152,0.000609,0.000819,0.00221,0.01075,0.045892,0.086967,0.11268,0.074659,0.0601,0.07556,0.065529,0.0663,0.063431,0.071627,0.091234,0.074635,0.039917,0.019221,0.015184,0.0113,0.006989,0.003822

In [19]:
extract_temporal_pattern("Holiday: Base")

,Year [note 2],Trip purpose,0000 to 0059 (%),0100 to 0159 (%),0200 to 0259 (%),0300 to 0359 (%),0400 to 0459 (%),0500 to 0559 (%),0600 to 0659 (%),0700 to 0759 (%),0800 to 0859 (%),0900 to 0959 (%),1000 to 1059 (%),1100 to 1159 (%),1200 to 1259 (%),1300 to 1359 (%),1400 to 1459 (%),1500 to 1559 (%),1600 to 1659 (%),1700 to 1759 (%),1800 to 1859 (%),1900 to 1959 (%),2000 to 2059 (%),2100 to 2159 (%),2200 to 2259 (%),2300 to 2359 (%)
7,2023 to 2024,"Holiday, Day Trip and Other",0.000273,0.000117,0.00024,0.000665,0.001823,0.006942,0.021378,0.047803,0.063796,0.077384,0.089399,0.08346,0.070076,0.071872,0.070719,0.077639,0.074445,0.070837,0.064082,0.05517,0.027522,0.012628,0.008782,0.002949

### 6.5 Behaviour Profile Construction

In [20]:
def construct_behaviour_profile(unified_purpose):
    """
    Construct the integrated behavioural profile
    for one unified trip purpose.

    The profile combines:
    - Baseline trip purpose probability (NTS0611)
    - Travel mode probability (NTS0409)
    - Temporal pattern probability (NTS0502)
    """

    baseline_profile = extract_baseline_profile(unified_purpose)

    travel_mode_profile = extract_travel_mode(unified_purpose)

    temporal_pattern_profile = extract_temporal_pattern(unified_purpose)

    return {
        "baseline_profile": baseline_profile,
        "travel_mode_profile": travel_mode_profile,
        "temporal_pattern_profile": temporal_pattern_profile
    }

In [21]:
business_profile = construct_behaviour_profile("Business")

business_profile.keys()

dict_keys(['baseline_profile', 'travel_mode_profile', 'temporal_pattern_profile'])

In [22]:
business_profile["baseline_profile"].head()

   Year Sex [note 2]    Age  Trip Purpose Probability
0  2024      Females    0-4                  0.000701
1  2024      Females   5-11                  0.000701
2  2024      Females  12-17                  0.001690
3  2024      Females  18-22                  0.015662
4  2024      Females  23-34                  0.030108

In [23]:
business_profile["travel_mode_profile"]

,Purpose,Bus in London,Car or van driver,Car or van passenger,London Underground,Motorcycle,Non-local bus,Other local bus,Other private transport [note 6],Other public transport [note 7],Pedal cycle [note 5],Surface Rail,Taxi or minicab,"Walk [notes 3, 4]"
0,Business,0.014149,0.68618,0.058015,0.02166,0.001818,0.0,0.022984,0.00744,0.002132,0.018543,0.068402,0.011831,0.086845

In [24]:
business_profile["temporal_pattern_profile"]

,Year [note 2],Trip purpose,0000 to 0059 (%),0100 to 0159 (%),0200 to 0259 (%),0300 to 0359 (%),0400 to 0459 (%),0500 to 0559 (%),0600 to 0659 (%),0700 to 0759 (%),0800 to 0859 (%),0900 to 0959 (%),1000 to 1059 (%),1100 to 1159 (%),1200 to 1259 (%),1300 to 1359 (%),1400 to 1459 (%),1500 to 1559 (%),1600 to 1659 (%),1700 to 1759 (%),1800 to 1859 (%),1900 to 1959 (%),2000 to 2059 (%),2100 to 2159 (%),2200 to 2259 (%),2300 to 2359 (%)
1,2023 to 2024,Business,0.000414,0.000152,0.000609,0.000819,0.00221,0.01075,0.045892,0.086967,0.11268,0.074659,0.0601,0.07556,0.065529,0.0663,0.063431,0.071627,0.091234,0.074635,0.039917,0.019221,0.015184,0.0113,0.006989,0.003822

In [25]:
all_behaviour_profiles = {}

for purpose in purpose_mapping:

    all_behaviour_profiles[purpose] = construct_behaviour_profile(purpose)

## 7. Validation

In [26]:
len(all_behaviour_profiles)

14

In [27]:
all_behaviour_profiles.keys()

dict_keys(['Commuting', 'Business', 'Education', 'Escort Education', 'Shopping', 'Other Escort', 'Personal Business', 'Visiting Friends at Private Home', 'Visiting Friends Elsewhere', 'Entertainment or Public Activity', 'Sport: Participate', 'Holiday: Base', 'Day Trip', 'Just Walk'])

In [28]:
all_behaviour_profiles["Personal Business"]

{'baseline_profile':     Year Sex [note 2]    Age  Trip Purpose Probability
 0   2024      Females    0-4                  0.075573
 1   2024      Females   5-11                  0.075573
 2   2024      Females  12-17                  0.074419
 3   2024      Females  18-22                  0.071061
 4   2024      Females  23-34                  0.074421
 5   2024      Females  35-49                  0.075522
 6   2024      Females  50-64                  0.105210
 7   2024      Females  65-74                  0.141740
 8   2024      Females    75+                  0.159272
 9   2024        Males    0-4                  0.068052
 10  2024        Males   5-11                  0.068052
 11  2024        Males  12-17                  0.070062
 12  2024        Males  18-22                  0.075539
 13  2024        Males  23-34                  0.068595
 14  2024        Males  35-49                  0.073757
 15  2024        Males  50-64                  0.089951
 16  2024        Males  65-74                  0.125429
 17  2024        Males    75+                  0.141036,
 'travel_mode_profile':              Purpose  Bus in London  Car or van driver  Car or van passenger  \
 7  Personal Business       0.016379           0.425456               0.22289

    London Underground  Motorcycle  Non-local bus  Other local bus  \
 7            0.006716    0.000799         0.0002         0.031427

    Other private transport [note 6]  Other public transport [note 7]  \
 7                          0.008118                         0.001792

    Pedal cycle [note 5]  Surface Rail  Taxi or minicab  Walk [notes 3, 4]
 7              0.009595      0.011557         0.014737           0.250334  ,
 'temporal_pattern_profile':   Year [note 2]                                    Trip purpose  \
 5  2023 to 2024  Other Work, Other Escort and Personal Business

    0000 to 0059 (%)  0100 to 0159 (%)  0200 to 0259 (%)  0300 to 0359 (%)  \
 5          0.000689          0.000234          0.000224          0.000071

    0400 to 0459 (%)  0500 to 0559 (%)  0600 to 0659 (%)  0700 to 0759 (%)  \
 5          0.000904          0.002833          0.009161          0.043429

    0800 to 0859 (%)  0900 to 0959 (%)  1000 to 1059 (%)  1100 to 1159 (%)  \
 5          0.093261          0.074097          0.076766          0.074615

    1200 to 1259 (%)  1300 to 1359 (%)  1400 to 1459 (%)  1500 to 1559 (%)  \
 5          0.081419          0.070155          0.067627          0.083308

    1600 to 1659 (%)  1700 to 1759 (%)  1800 to 1859 (%)  1900 to 1959 (%)  \
 5          0.090202          0.085803          0.059412          0.039304

    2000 to 2059 (%)  2100 to 2159 (%)  2200 to 2259 (%)  2300 to 2359 (%)
 5          0.023725           0.01153          0.007551          0.003681  }

In [29]:
for purpose, profile in all_behaviour_profiles.items():
    print(
        purpose,
        len(profile["baseline_profile"]),
        len(profile["travel_mode_profile"]),
        len(profile["temporal_pattern_profile"])
    )

Commuting 18 1 1
Business 18 1 1
Education 18 1 1
Escort Education 18 1 1
Shopping 18 1 1
Other Escort 18 1 1
Personal Business 18 1 1
Visiting Friends at Private Home 18 1 1
Visiting Friends Elsewhere 18 1 1
Entertainment or Public Activity 18 1 1
Sport: Participate 18 1 1
Holiday: Base 18 1 1
Day Trip 18 1 1
Just Walk 18 1 1

## 8. Export

In [30]:
# ==========================================
# Export Behaviour Profiles
# ==========================================

import json

export_profiles = {}

for purpose, profile in all_behaviour_profiles.items():

    export_profiles[purpose] = {

        "baseline_profile": profile["baseline_profile"].to_dict(
            orient="records"
        ),

        "travel_mode_profile": profile["travel_mode_profile"].to_dict(
            orient="records"
        ),

        "temporal_pattern_profile": profile["temporal_pattern_profile"].to_dict(
            orient="records"
        )

    }

output_path = "../../outputs/behaviour_profiles.json"

with open(output_path, "w", encoding="utf-8") as f:

    json.dump(export_profiles, f, indent=4)

print(f"Behaviour profiles exported to:\n{output_path}")

Behaviour profiles exported to:
../../outputs/behaviour_profiles.json

In [31]:
# ==========================================
# Validation
# ==========================================

with open("../../outputs/behaviour_profiles.json", "r", encoding="utf-8") as f:

    behaviour_profiles = json.load(f)

print(behaviour_profiles.keys())

dict_keys(['Commuting', 'Business', 'Education', 'Escort Education', 'Shopping', 'Other Escort', 'Personal Business', 'Visiting Friends at Private Home', 'Visiting Friends Elsewhere', 'Entertainment or Public Activity', 'Sport: Participate', 'Holiday: Base', 'Day Trip', 'Just Walk'])