## Overview

This notebook integrates the processed demographic datasets into a unified representative population pool. The resulting population pool serves as the demographic foundation for the subsequent Behaviour Layer, Opportunity Layer, and mobility simulation framework.

Input datasets:

- Age
- Sex
- Household Composition
- Economic Activity Status
- Industry
- Car Ownership
- Distance Travelled to Work
- Ethnic Group

Output:

- Representative Population Pool

## 1. Import Libraries

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

## 2. Set Up File Pathes

In [2]:
from pathlib import Path

project_root = Path.cwd().parents[1]

processed_demographic_path = (
    project_root
    / "data"
    / "demographic"
    / "processed"
)

processed_mobility_path = (
    project_root
    / "data"
    / "mobility"
    / "processed"
)

output_path = (
    project_root
    / "output"
    / "demographic_profiles"
)

output_path.mkdir(parents=True, exist_ok=True)

## 3. Load Dataset

In [3]:
# Age
age_file = (
    processed_demographic_path
    / "age"
    / "age.json"
)

# Gender
gender_file = (
    processed_demographic_path
    / "gender"
    / "gender.json"
)

# Household Composition
household_file = (
    processed_demographic_path
    / "household_by_age"
    / "household_by_age.json"
)

# Economic Activity Status
economic_activity_file = (
    processed_demographic_path
    / "economic_activity_status"
    / "economic_activity_status.json"
)

# Industry
industry_file = (
    processed_demographic_path
    / "industry"
    / "industry_by_age.json"
)

# Car Ownership
car_ownership_file = (
    processed_demographic_path
    / "car_ownership"
    / "car_ownership.json"
)

# Distance Travelled to Work
travel_distance_file = (
    project_root
    / "data"
    / "mobility"
    / "processed"
    / "travel_distance"
    / "travel_distance_by_age.json"
)

# Ethnic Group
ethnic_group_file = (
    processed_demographic_path
    / "ethnic_group"
    / "ethnic_group_by_age.json"
)

In [4]:
age = pd.read_json(age_file)

gender = pd.read_json(gender_file)

household = pd.read_json(household_file)

economic_activity = pd.read_json(economic_activity_file)

industry = pd.read_json(industry_file)

car_ownership = pd.read_json(car_ownership_file)

travel_distance = pd.read_json(travel_distance_file)

ethnic_group = pd.read_json(ethnic_group_file)

## 4. Integration

In [5]:
display(age.head())

display(gender.head())

display(household.head())

display(economic_activity.head())

display(industry.head())

display(car_ownership.head())

display(travel_distance.head())

display(ethnic_group.head())

  Lower tier local authorities Age Group  Observation
0                   Manchester       0-4        34378
1                   Manchester      5-11        51349
2                   Manchester     12-17        41226
3                   Manchester     18-22        61780
4                   Manchester     23-34       123440

  Lower tier local authorities Sex (2 categories) Age Group  Observation
0                   Manchester             Female       0-4        17115
1                   Manchester               Male       0-4        17263
2                   Manchester             Female      5-11        25072
3                   Manchester               Male      5-11        26277
4                   Manchester             Female     12-17        20286

,Lower tier local authorities,Household Type,Age Group,Observation
0,Manchester,Couple household: All children non-dependent,0-4,0
1,Manchester,Couple household: All children non-dependent,12-17,107
2,Manchester,Couple household: All children non-dependent,18-22,3313
3,Manchester,Couple household: All children non-dependent,23-34,7200
4,Manchester,Couple household: All children non-dependent,35-49,4158

,Lower tier local authorities,Economic activity status (7 categories),Age Group,Observation
0,Manchester,Does not apply,0-4,34378
1,Manchester,Economically active and a full-time student: I...,0-4,0
2,Manchester,Economically inactive (excluding full-time stu...,0-4,0
3,Manchester,Economically active and a full-time student: U...,0-4,0
4,Manchester,Economically inactive and a full-time student,0-4,0

,Lower tier local authorities,Industry (current) (19 categories),Age Group,Observation
0,Manchester,"A Agriculture, forestry and fishing",0-4,0
1,Manchester,F Construction,0-4,0
2,Manchester,O Public administration and defence; compulsor...,0-4,0
3,Manchester,N Administrative and support service activities,0-4,0
4,Manchester,H Transport and storage,0-4,0

,local authority: district / unitary (as of April 2023),Total: All households,No cars or vans in household,1 car or van in household,2 cars or vans in household,3 or more cars or vans in household
0,Manchester,214732,83770,92267,31611,7084

  Age_Group Distance travelled to work  Observation
0       0-4     10km to less than 30km            0
1       0-4     30km to less than 60km            0
2       0-4      5km to less than 10km            0
3       0-4              60km and over            0
4       0-4             Does not apply        34378

,Lower tier local authorities,Ethnic Group,Age Group,Observation
0,Manchester,"Asian, Asian British or Asian Welsh: Bangladeshi",0-4,833
1,Manchester,"Black, Black British, Black Welsh, Caribbean o...",0-4,3717
2,Manchester,"Asian, Asian British or Asian Welsh: Other Asian",0-4,1030
3,Manchester,White: Irish,0-4,95
4,Manchester,"Black, Black British, Black Welsh, Caribbean o...",0-4,438

In [6]:
print(age.shape)
print(gender.shape)
print(household.shape)
print(economic_activity.shape)
print(industry.shape)
print(car_ownership.shape)
print(travel_distance.shape)
print(ethnic_group.shape)

(9, 3)
(18, 4)
(81, 4)
(63, 4)
(171, 4)
(1, 6)
(72, 3)
(180, 4)

## 5. Validation

### 6. Export