## Overview

This notebook integrates the processed demographic datasets into a unified representative population pool. The resulting population pool serves as the demographic foundation for the subsequent Behaviour Layer, Opportunity Layer, and mobility simulation framework. The representative population pool is a complete demographic state space generated by integrating all processed demographic datasets without applying behavioural or logical constraints.

All demographic categories are retained, including those with zero counts, to preserve the complete representative state space. Zero counts indicate that the corresponding demographic combination is not supported by the source dataset rather than being removed during preprocessing.

Input datasets:

- Age
- Sex
- Household Composition
- Economic Activity Status
- Industry
- Car Ownership
- Distance Travelled to Work
- Ethnic Group

Output:

- Representative Population Pool

## 1. Import Libraries

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

## 2. Set Up File Pathes

In [2]:
from pathlib import Path

project_root = Path.cwd().parents[1]

processed_demographic_path = (
    project_root
    / "data"
    / "demographic"
    / "processed"
)

processed_mobility_path = (
    project_root
    / "data"
    / "mobility"
    / "processed"
)

output_path = (
    project_root
    / "output"
    / "demographic_profiles"
)

output_path.mkdir(parents=True, exist_ok=True)

## 3. Load Dataset

In [3]:
# Age
age_file = (
    processed_demographic_path
    / "age"
    / "age.json"
)

# Gender
gender_file = (
    processed_demographic_path
    / "gender"
    / "gender.json"
)

# Household Composition
household_file = (
    processed_demographic_path
    / "household_by_age"
    / "household_by_age.json"
)

# Economic Activity Status
economic_activity_file = (
    processed_demographic_path
    / "economic_activity_status"
    / "economic_activity_status.json"
)

# Industry
industry_file = (
    processed_demographic_path
    / "industry"
    / "industry_by_age.json"
)

# Car Ownership
car_ownership_file = (
    processed_demographic_path
    / "car_ownership_by_household"
    / "car_ownership_by_household.json"
)

# Distance Travelled to Work
travel_distance_file = (
    project_root
    / "data"
    / "mobility"
    / "processed"
    / "travel_distance"
    / "travel_distance_by_age.json"
)

# Ethnic Group
ethnic_group_file = (
    processed_demographic_path
    / "ethnic_group"
    / "ethnic_group_by_age.json"
)

In [4]:
age = pd.read_json(age_file)

gender = pd.read_json(gender_file)

household = pd.read_json(household_file)

economic_activity = pd.read_json(economic_activity_file)

industry = pd.read_json(industry_file)

car_ownership = pd.read_json(car_ownership_file)

travel_distance = pd.read_json(travel_distance_file)

ethnic_group = pd.read_json(ethnic_group_file)

In [5]:
display(age.head())

display(gender.head())

display(household.head())

display(economic_activity.head())

display(industry.head())

display(car_ownership.head())

display(travel_distance.head())

display(ethnic_group.head())

  Lower tier local authorities    Age  Population
0                   Manchester    0-4       34378
1                   Manchester   5-11       51349
2                   Manchester  12-17       41226
3                   Manchester  18-22       61780
4                   Manchester  23-34      123440

  Lower tier local authorities  Gender    Age  Gender Population
0                   Manchester  Female    0-4              17115
1                   Manchester    Male    0-4              17263
2                   Manchester  Female   5-11              25072
3                   Manchester    Male   5-11              26277
4                   Manchester  Female  12-17              20286

,Lower tier local authorities,Household Type,Age,Household Count
0,Manchester,Couple household: All children non-dependent,0-4,0
1,Manchester,Couple household: All children non-dependent,12-17,107
2,Manchester,Couple household: All children non-dependent,18-22,3313
3,Manchester,Couple household: All children non-dependent,23-34,7200
4,Manchester,Couple household: All children non-dependent,35-49,4158

,Lower tier local authorities,Economic Activity Status,Age,Economic Count
0,Manchester,Does not apply,0-4,34378
1,Manchester,Economically active and a full-time student: I...,0-4,0
2,Manchester,Economically inactive (excluding full-time stu...,0-4,0
3,Manchester,Economically active and a full-time student: U...,0-4,0
4,Manchester,Economically inactive and a full-time student,0-4,0

,Lower tier local authorities,Industry,Age,Industry Count
0,Manchester,"A Agriculture, forestry and fishing",0-4,0
1,Manchester,F Construction,0-4,0
2,Manchester,O Public administration and defence; compulsor...,0-4,0
3,Manchester,N Administrative and support service activities,0-4,0
4,Manchester,H Transport and storage,0-4,0

,Lower tier local authorities,Car Ownership,Household Type,Car Ownership Count
0,Manchester,No cars or vans in household,One-person household,12424
1,Manchester,No cars or vans in household,One-person household,29821
2,Manchester,No cars or vans in household,Older family household,1637
3,Manchester,No cars or vans in household,Couple household: No children,2708
4,Manchester,No cars or vans in household,Couple household: With dependent children,3796

   Age Distance travelled to work  Travel Distance Count
0  0-4     10km to less than 30km                      0
1  0-4     30km to less than 60km                      0
2  0-4      5km to less than 10km                      0
3  0-4              60km and over                      0
4  0-4             Does not apply                  34378

,Lower tier local authorities,Ethnic Group,Age,Ethnic Count
0,Manchester,"Asian, Asian British or Asian Welsh: Bangladeshi",0-4,833
1,Manchester,"Black, Black British, Black Welsh, Caribbean o...",0-4,3717
2,Manchester,"Asian, Asian British or Asian Welsh: Other Asian",0-4,1030
3,Manchester,White: Irish,0-4,95
4,Manchester,"Black, Black British, Black Welsh, Caribbean o...",0-4,438

In [6]:
print(age.shape)
print(gender.shape)
print(household.shape)
print(economic_activity.shape)
print(industry.shape)
print(car_ownership.shape)
print(travel_distance.shape)
print(ethnic_group.shape)

(9, 3)
(18, 4)
(81, 4)
(63, 4)
(171, 4)
(56, 4)
(72, 3)
(180, 4)

## 4. Initialise Representative Population Pool

In [7]:
population_pool = age[["Age"]].copy()

display(population_pool)

print(population_pool.shape)

     Age
0    0-4
1   5-11
2  12-17
3  18-22
4  23-34
5  35-49
6  50-64
7  65-74
8    75+

(9, 1)

## 5. Expand Gender Profiles

In [8]:
population_pool = population_pool.merge(
    gender[["Age","Gender"]],
    on="Age",
    how="left"
)

In [9]:
display(population_pool)

print(population_pool.shape)

      Age  Gender
0     0-4  Female
1     0-4    Male
2    5-11  Female
3    5-11    Male
4   12-17  Female
5   12-17    Male
6   18-22  Female
7   18-22    Male
8   23-34  Female
9   23-34    Male
10  35-49  Female
11  35-49    Male
12  50-64  Female
13  50-64    Male
14  65-74  Female
15  65-74    Male
16    75+  Female
17    75+    Male

(18, 2)

## 6. Expand Household Profiles

In [10]:
population_pool = population_pool.merge(
    household[["Age", "Household Type", "Household Count"]],
    on="Age",
    how="left"
)

display(population_pool.head())

print(population_pool.shape)

,Age,Gender,Household Type,Household Count
0,0-4,Female,Couple household: All children non-dependent,0
1,0-4,Female,Couple household: No children,0
2,0-4,Female,Couple household: With dependent children,20814
3,0-4,Female,Lone parent household: All children non-dependent,0
4,0-4,Female,Lone parent household: With dependent children,7992

(162, 4)

## 7. Expand Economic Activity Profiles

In [11]:
population_pool = population_pool.merge(
    economic_activity[["Age", "Economic Activity Status", "Economic Count"]],
    on="Age",
    how="left"
)

display(population_pool.head())

print(population_pool.shape)

,Age,Gender,Household Type,Household Count,Economic Activity Status,Economic Count
0,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378
1,0-4,Female,Couple household: All children non-dependent,0,Economically active and a full-time student: I...,0
2,0-4,Female,Couple household: All children non-dependent,0,Economically inactive (excluding full-time stu...,0
3,0-4,Female,Couple household: All children non-dependent,0,Economically active and a full-time student: U...,0
4,0-4,Female,Couple household: All children non-dependent,0,Economically inactive and a full-time student,0

(1134, 6)

## 8. Expand Industry Profiles

In [12]:
population_pool = population_pool.merge(
    industry[["Age", "Industry", "Industry Count"]],
    on=["Age"],
    how="left"
)

In [13]:
display(population_pool.head())

print(population_pool.shape)

,Age,Gender,Household Type,Household Count,Economic Activity Status,Economic Count,Industry,Industry Count
0,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,"A Agriculture, forestry and fishing",0
1,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,F Construction,0
2,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,O Public administration and defence; compulsor...,0
3,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,N Administrative and support service activities,0
4,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,H Transport and storage,0

(21546, 8)

## 9. Expand Ethnic Group Profiles

The representative population pool is expanded by integrating ethnic group information.

Each representative profile is matched by age group and expanded to include all ethnic group categories supported by the processed dataset.

In [14]:
population_pool = population_pool.merge(
    ethnic_group[["Age", "Ethnic Group", "Ethnic Count"]],
    on="Age",
    how="left"
)

display(population_pool.head())

print(population_pool.shape)

,Age,Gender,Household Type,Household Count,Economic Activity Status,Economic Count,Industry,Industry Count,Ethnic Group,Ethnic Count
0,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,"A Agriculture, forestry and fishing",0,"Asian, Asian British or Asian Welsh: Bangladeshi",833
1,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,"A Agriculture, forestry and fishing",0,"Black, Black British, Black Welsh, Caribbean o...",3717
2,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,"A Agriculture, forestry and fishing",0,"Asian, Asian British or Asian Welsh: Other Asian",1030
3,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,"A Agriculture, forestry and fishing",0,White: Irish,95
4,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,"A Agriculture, forestry and fishing",0,"Black, Black British, Black Welsh, Caribbean o...",438

(430920, 10)

## 10. Expand Travel Distance Profiles

In [15]:
population_pool = population_pool.merge(
    travel_distance[
        ["Age", "Distance travelled to work", "Travel Distance Count"]
    ],
    on="Age",
    how="left"
)

In [16]:
display(population_pool.head())
print(population_pool.shape)

,Age,Gender,Household Type,Household Count,Economic Activity Status,Economic Count,Industry,Industry Count,Ethnic Group,Ethnic Count,Distance travelled to work,Travel Distance Count
0,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,"A Agriculture, forestry and fishing",0,"Asian, Asian British or Asian Welsh: Bangladeshi",833,10km to less than 30km,0
1,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,"A Agriculture, forestry and fishing",0,"Asian, Asian British or Asian Welsh: Bangladeshi",833,30km to less than 60km,0
2,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,"A Agriculture, forestry and fishing",0,"Asian, Asian British or Asian Welsh: Bangladeshi",833,5km to less than 10km,0
3,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,"A Agriculture, forestry and fishing",0,"Asian, Asian British or Asian Welsh: Bangladeshi",833,60km and over,0
4,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,"A Agriculture, forestry and fishing",0,"Asian, Asian British or Asian Welsh: Bangladeshi",833,Does not apply,34378

(3447360, 12)

## 11. Expand Car Ownership Profiles

In [17]:
population_pool = population_pool.merge(
    car_ownership,
    on="Household Type",
    how="left"
)

population_pool = population_pool.drop(
    columns=["Lower tier local authorities"]
)

In [22]:
display(population_pool.head(15))
print(population_pool.shape)

,Age,Gender,Household Type,Household Count,Economic Activity Status,Economic Count,Industry,Industry Count,Ethnic Group,Ethnic Count,Distance travelled to work,Travel Distance Count,Car Ownership,Car Ownership Count
0,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,"A Agriculture, forestry and fishing",0,"Asian, Asian British or Asian Welsh: Bangladeshi",833,10km to less than 30km,0,No cars or vans in household,792
1,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,"A Agriculture, forestry and fishing",0,"Asian, Asian British or Asian Welsh: Bangladeshi",833,10km to less than 30km,0,No cars or vans in household,221
2,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,"A Agriculture, forestry and fishing",0,"Asian, Asian British or Asian Welsh: Bangladeshi",833,10km to less than 30km,0,1 car or van in household,2627
3,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,"A Agriculture, forestry and fishing",0,"Asian, Asian British or Asian Welsh: Bangladeshi",833,10km to less than 30km,0,1 car or van in household,512
4,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,"A Agriculture, forestry and fishing",0,"Asian, Asian British or Asian Welsh: Bangladeshi",833,10km to less than 30km,0,2 cars or vans in household,2614
5,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,"A Agriculture, forestry and fishing",0,"Asian, Asian British or Asian Welsh: Bangladeshi",833,10km to less than 30km,0,2 cars or vans in household,420
6,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,"A Agriculture, forestry and fishing",0,"Asian, Asian British or Asian Welsh: Bangladeshi",833,10km to less than 30km,0,3 or more cars or vans in household,1487
7,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,"A Agriculture, forestry and fishing",0,"Asian, Asian British or Asian Welsh: Bangladeshi",833,10km to less than 30km,0,3 or more cars or vans in household,236
8,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,"A Agriculture, forestry and fishing",0,"Asian, Asian British or Asian Welsh: Bangladeshi",833,30km to less than 60km,0,No cars or vans in household,792
9,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,"A Agriculture, forestry and fishing",0,"Asian, Asian British or Asian Welsh: Bangladeshi",833,30km to less than 60km,0,No cars or vans in household,221
10,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,"A Agriculture, forestry and fishing",0,"Asian, Asian British or Asian Welsh: Bangladeshi",833,30km to less than 60km,0,1 car or van in household,2627
11,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,"A Agriculture, forestry and fishing",0,"Asian, Asian British or Asian Welsh: Bangladeshi",833,30km to less than 60km,0,1 car or van in household,512
12,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,"A Agriculture, forestry and fishing",0,"Asian, Asian British or Asian Welsh: Bangladeshi",833,30km to less than 60km,0,2 cars or vans in household,2614
13,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,"A Agriculture, forestry and fishing",0,"Asian, Asian British or Asian Welsh: Bangladeshi",833,30km to less than 60km,0,2 cars or vans in household,420
14,0-4,Female,Couple household: All children non-dependent,0,Does not apply,34378,"A Agriculture, forestry and fishing",0,"Asian, Asian British or Asian Welsh: Bangladeshi",833,30km to less than 60km,0,3 or more cars or vans in household,1487

(21450240, 14)

## 12. Validate Representative Population Pool

In [19]:
def validate_dataset(pool, source, keys, count_col, dataset_name):
    source_total = source[count_col].sum()

    pool_total = (
        pool[keys + [count_col]]
        .drop_duplicates()
        [count_col]
        .sum()
    )

    print(f"\n{dataset_name}")
    print(f"Source : {source_total:,}")
    print(f"Pool   : {pool_total:,}")

    if source_total == pool_total:
        print("✅ PASS")
    else:
        print("❌ FAIL")

In [20]:
validate_dataset(
    population_pool,
    household,
    ["Age", "Household Type"],
    "Household Count",
    "Household"
)

validate_dataset(
    population_pool,
    economic_activity,
    ["Age", "Economic Activity Status"],
    "Economic Count",
    "Economic"
)

validate_dataset(
    population_pool,
    industry,
    ["Age", "Industry"],
    "Industry Count",
    "Industry"
)

validate_dataset(
    population_pool,
    ethnic_group,
    ["Age", "Ethnic Group"],
    "Ethnic Count",
    "Ethnic"
)

validate_dataset(
    population_pool,
    travel_distance,
    ["Age", "Distance travelled to work"],
    "Travel Distance Count",
    "Travel Distance"
)

validate_dataset(
    population_pool,
    car_ownership,
    ["Household Type", "Car Ownership"],
    "Car Ownership Count",
    "Car Ownership"
)

Household
Source : 530,137
Pool   : 530,137
✅ PASS

Economic
Source : 551,947
Pool   : 551,947
✅ PASS

Industry
Source : 551,945
Pool   : 551,945
✅ PASS

Ethnic
Source : 551,947
Pool   : 551,947
✅ PASS

Travel Distance
Source : 551,947
Pool   : 551,947
✅ PASS

Car Ownership
Source : 214,735
Pool   : 214,735
✅ PASS

## 13. Export Representative Population Pool

The validated representative population pool was exported after the integration and validation processes were completed.

Two output formats were generated for different purposes:

- **JSON** (`representative_population_pool.json`) was produced as a human-readable representation of the complete representative population pool and for interoperability with other applications.
- **Parquet** (`representative_population_pool.parquet`) was additionally exported as the primary storage format for subsequent framework development because it provides significantly faster read/write performance and more efficient storage for large-scale tabular data.

The representative population pool contains over 21 million representative profiles generated from the combination of demographic attributes and associated mobility-related characteristics. Since the dataset is automatically generated from the processed demographic datasets, it is treated as an output artefact rather than a source file and is therefore excluded from version control.

In [21]:
representative_population_pool = population_pool.copy()

representative_population_pool.to_parquet(
    output_path / "representative_population_pool.parquet",
    index=False,
    compression="zstd"
)