# Demographic Dataset Processing

## Overview

This notebook processes a single demographic dataset obtained from the UK Census.

The objective is to clean, reorganise, and extract the required demographic information for the representative population generation framework.

The processed dataset will be exported as a standardised JSON file for later integration.

---

## Dataset Information

| Item | Description |
|------|-------------|
| Dataset |TS045_Car_or_van_availability |
| Source | Office for National Statistics (ONS) Census 2021 |
| Geography | local authorities: district / unitary (as of April 2023) |
| Input File |TS045_Car_or_van_availability |
| Output File |car_ownership.json |
| Notebook Author | Peter |
| Last Updated |2026-07-13 |

## 1. Import

In [1]:
# Import libraries

import pandas as pd
import numpy as np
import json
from pathlib import Path

In [2]:
# Display settings

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

## 2. Configuration

Specify the input dataset and output location.

In [3]:
# File paths

input_file = "TS045_Car_or_van_availability.xlsx"
output_file = "car_ownership.json"

raw_data_path = Path("../../data/demographic/raw/car_ownership/")
output_data_path = Path("../../data/demographic/processed/car_ownership/")

## 3. Load Dataset

In [4]:
df = pd.read_excel(raw_data_path / input_file, skiprows=7)
df_processed = df.copy()

df_processed.head()

c:\Users\user\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,local authority: district / unitary (as of April 2023),Total: All households,No cars or vans in household,1 car or van in household,2 cars or vans in household,3 or more cars or vans in household
0,Hartlepool,40930.0,12102.0,16635.0,9259.0,2934.0
1,Middlesbrough,60263.0,19964.0,24144.0,12572.0,3583.0
2,Redcar and Cleveland,61638.0,15288.0,26089.0,15288.0,4973.0
3,Stockton-on-Tees,83756.0,18713.0,34299.0,23675.0,7069.0
4,Darlington,48918.0,12253.0,21342.0,11906.0,3417.0

## 4. Dataset Exploration

Inspect the structure of the dataset before processing.

In [5]:
df_processed.info()

df_processed.shape

df_processed.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 6 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   local authority: district / unitary (as of April 2023)  319 non-null    object
 1   Total: All households                                   318 non-null    float64
 2   No cars or vans in household                            318 non-null    float64
 3   1 car or van in household                               318 non-null    float64
 4   2 cars or vans in household                             318 non-null    float64
 5   3 or more cars or vans in household                     318 non-null    float64
dtypes: float64(5), object(1)
memory usage: 15.1+ KB

Index(['local authority: district / unitary (as of April 2023)',
       'Total: All households', 'No cars or vans in household',
       '1 car or van in household', '2 cars or vans in household',
       '3 or more cars or vans in household'],
      dtype='object')

In [6]:
df_processed.describe(include="all")

,local authority: district / unitary (as of April 2023),Total: All households,No cars or vans in household,1 car or van in household,2 cars or vans in household,3 or more cars or vans in household
count,319,318.000000,318.000000,318.000000,318.000000,318.000000
unique,319,NaN,NaN,NaN,NaN,NaN
top,In order to protect against disclosure of pers...,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN
mean,NaN,77934.562893,18169.685535,32191.512579,20395.374214,7177.990566
std,NaN,51031.877245,17946.266935,21431.407530,13305.628909,4862.905956
min,NaN,941.000000,393.000000,360.000000,123.000000,43.000000
25%,NaN,45615.000000,6902.000000,18859.000000,12708.500000,4508.750000
50%,NaN,61439.000000,11012.500000,25056.000000,16942.500000,6249.000000
75%,NaN,96439.250000,23749.500000,41294.500000,22650.500000,8243.000000
max,NaN,423456.000000,134123.000000,176325.000000,86325.000000,33861.000000

## 5. Data Cleaning

Perform dataset-specific cleaning operations.

Typical tasks include:

- Rename variables
- Remove unnecessary columns
- Handle missing values
- Convert data types
- Standardise labels

In [7]:
# Cleaning code

## 6. Feature Processing

Extract the demographic information required by the framework.

Examples include:

- Age groups
- Household composition
- Occupation
- Industry
- Car ownership
- Student status

The processing steps in this section depend on the current dataset.

In [8]:
# Dataset-specific processing
def get_car_ownership_distribution(local_authority):
    return df_processed[df_processed['local authority: district / unitary (as of April 2023)'] == local_authority]

In [9]:
get_car_ownership_distribution("Manchester")

,local authority: district / unitary (as of April 2023),Total: All households,No cars or vans in household,1 car or van in household,2 cars or vans in household,3 or more cars or vans in household
34,Manchester,214732.0,83770.0,92267.0,31611.0,7084.0

## 7. Validation

Verify that the processed dataset is internally consistent before exporting.

In [10]:
# Examples

df_processed.head()

df_processed.info()

df_processed.isna().sum()

# Additional validation here

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 6 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   local authority: district / unitary (as of April 2023)  319 non-null    object
 1   Total: All households                                   318 non-null    float64
 2   No cars or vans in household                            318 non-null    float64
 3   1 car or van in household                               318 non-null    float64
 4   2 cars or vans in household                             318 non-null    float64
 5   3 or more cars or vans in household                     318 non-null    float64
dtypes: float64(5), object(1)
memory usage: 15.1+ KB

local authority: district / unitary (as of April 2023)    1
Total: All households                                     2
No cars or vans in household                              2
1 car or van in household                                 2
2 cars or vans in household                               2
3 or more cars or vans in household                       2
dtype: int64

## 8. Export Processed Dataset

In [12]:
output_data_path.mkdir(parents=True, exist_ok=True)

# Example

# df_processed.to_json(
#     output_data_path / output_file,
#     orient="records",
#     indent=4
# )

df_car_ownership = get_car_ownership_distribution("Manchester")
df_car_ownership.to_json(
    output_data_path / output_file,
    orient="records",
    indent=4
)

## Summary

### Input

-

### Output

-

### Processing Completed

- Dataset loaded
- Dataset cleaned
- Features extracted
- Validation completed
- JSON exported