# Demographic Dataset Processing

## Overview

This notebook processes a single demographic dataset obtained from the UK Census.

The objective is to clean, reorganise, and extract the required demographic information for the representative population generation framework.

The processed dataset will be exported as a standardised JSON file for later integration.

---

## Dataset Information

| Item | Description |
|------|-------------|
| Dataset |RM032-Ethnic_group_by_age |
| Source | Office for National Statistics (ONS) Census 2021 |
| Geography | local authorities: district / unitary (as of April 2023) |
| Input File | RM032_Ethnic_group_by_age|
| Output File |ethnic_group_by_age.json|
| Notebook Author | Peter |
| Last Updated | |

## 1. Import

In [1]:
# Import libraries

import pandas as pd
import numpy as np
import json

In [2]:
import sys
from pathlib import Path

# Find repository root (../..)
repo_root = Path.cwd().parents[1]

# Add repository root to Python import path
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))

In [3]:
# Display settings

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

## 2. Configuration

Specify the input dataset and output location.

In [4]:
# File paths

input_file = "RM032_Ethnic_group_by_age.xlsx"
output_file = "ethnic_group_by_age.json"

raw_data_path = Path("../../data/demographic/raw/ethnic_group")
output_data_path = Path("../../data/demographic/processed/ethnic_group")

## 3. Load Dataset

In [5]:
df = pd.read_excel(raw_data_path / input_file)
df_processed = df.copy()

df_processed.head()

,Lower tier local authorities Code,Lower tier local authorities,Ethnic group (20 categories) Code,Ethnic group (20 categories),Age (C) (5 categories) Code,Age (C) (5 categories),Observation
0,E06000001,Hartlepool,-8,Does not apply,1,Aged 24 years and under,0
1,E06000001,Hartlepool,-8,Does not apply,2,Aged 25 to 34 years,0
2,E06000001,Hartlepool,-8,Does not apply,3,Aged 35 to 49 years,0
3,E06000001,Hartlepool,-8,Does not apply,4,Aged 50 to 64 years,0
4,E06000001,Hartlepool,-8,Does not apply,5,Aged 65 years and over,0

## 4. Dataset Exploration

Inspect the structure of the dataset before processing.

In [6]:
df_processed.info()

df_processed.shape

df_processed.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33100 entries, 0 to 33099
Data columns (total 7 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Lower tier local authorities Code  33100 non-null  object
 1   Lower tier local authorities       33100 non-null  object
 2   Ethnic group (20 categories) Code  33100 non-null  int64
 3   Ethnic group (20 categories)       33100 non-null  object
 4   Age (C) (5 categories) Code        33100 non-null  int64
 5   Age (C) (5 categories)             33100 non-null  object
 6   Observation                        33100 non-null  int64
dtypes: int64(3), object(4)
memory usage: 1.8+ MB

Index(['Lower tier local authorities Code', 'Lower tier local authorities',
       'Ethnic group (20 categories) Code', 'Ethnic group (20 categories)',
       'Age (C) (5 categories) Code', 'Age (C) (5 categories)', 'Observation'],
      dtype='object')

In [7]:
df_processed.describe(include="all")

,Lower tier local authorities Code,Lower tier local authorities,Ethnic group (20 categories) Code,Ethnic group (20 categories),Age (C) (5 categories) Code,Age (C) (5 categories),Observation
count,33100,33100,33100.000000,33100,33100.000000,33100,33100.000000
unique,331,331,NaN,20,NaN,5,NaN
top,W06000024,Merthyr Tydfil,NaN,Does not apply,NaN,Aged 24 years and under,NaN
freq,100,100,NaN,1655,NaN,6620,NaN
mean,NaN,NaN,9.100000,NaN,3.000000,NaN,1800.527855
std,NaN,NaN,6.625053,NaN,1.414235,NaN,7277.970073
min,NaN,NaN,-8.000000,NaN,1.000000,NaN,0.000000
25%,NaN,NaN,4.750000,NaN,2.000000,NaN,25.000000
50%,NaN,NaN,9.500000,NaN,3.000000,NaN,91.000000
75%,NaN,NaN,14.250000,NaN,4.000000,NaN,397.000000
max,NaN,NaN,19.000000,NaN,5.000000,NaN,175539.000000

## 5. Data Cleaning

Perform dataset-specific cleaning operations.

Typical tasks include:

- Rename variables
- Remove unnecessary columns
- Handle missing values
- Convert data types
- Standardise labels

In [8]:
# Cleaning code

## 6. Feature Processing

Extract the demographic information required by the framework.

Examples include:

- Age groups
- Household composition
- Occupation
- Industry
- Car ownership
- Student status

The processing steps in this section depend on the current dataset.

In [9]:
# Dataset-specific processing

## 7. Validation

Verify that the processed dataset is internally consistent before exporting.

In [10]:
# Examples

df_processed.head()

df_processed.info()

df_processed.isna().sum()

# Additional validation here

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33100 entries, 0 to 33099
Data columns (total 7 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Lower tier local authorities Code  33100 non-null  object
 1   Lower tier local authorities       33100 non-null  object
 2   Ethnic group (20 categories) Code  33100 non-null  int64
 3   Ethnic group (20 categories)       33100 non-null  object
 4   Age (C) (5 categories) Code        33100 non-null  int64
 5   Age (C) (5 categories)             33100 non-null  object
 6   Observation                        33100 non-null  int64
dtypes: int64(3), object(4)
memory usage: 1.8+ MB

Lower tier local authorities Code    0
Lower tier local authorities         0
Ethnic group (20 categories) Code    0
Ethnic group (20 categories)         0
Age (C) (5 categories) Code          0
Age (C) (5 categories)               0
Observation                          0
dtype: int64

## 8. Export Processed Dataset

In [11]:
output_data_path.mkdir(parents=True, exist_ok=True)

# Example

# df_processed.to_json(
#     output_data_path / output_file,
#     orient="records",
#     indent=4
# )

## Summary

### Input

-

### Output

-

### Processing Completed

- Dataset loaded
- Dataset cleaned
- Features extracted
- Validation completed
- JSON exported